const Flexiblepricedata=[
    {
        images:"images/flaxible-price-image1.png",
        price:"$20",
        title:"Daily Pass",
        des:"Our Best Plan for Individuals",
        WorkingHours:"Working Hours",
        des2:"One Time 24 hours access",
        MeetingRoom:"Meeting Room",
        des3:"Additional charge $5/Per hour",
        Essentials:"Essentials",
        des4:"Internet, A/C, Cofee machines ...",
        Administration:"Administration",
        des5:"Instant current month upgrades",
    },
    {
        images:"images/flaxible-price-image2.png",
        price:"$20",
        title:"Daily Pass",
        des:"Our Best Plan for Individuals",
        WorkingHours:"Working Hours",
        des2:"One Time 24 hours access",
        MeetingRoom:"Meeting Room",
        des3:"Additional charge $5/Per hour",
        Essentials:"Essentials",
        des4:"Internet, A/C, Cofee machines ...",
        Administration:"Administration",
        des5:"Instant current month upgrades",
    },
    {
        images:"images/flaxible-price-image3.png",
        price:"$20",
        title:"Daily Pass",
        des:"Our Best Plan for Individuals",
        WorkingHours:"Working Hours",
        des2:"One Time 24 hours access",
        MeetingRoom:"Meeting Room",
        des3:"Additional charge $5/Per hour",
        Essentials:"Essentials",
        des4:"Internet, A/C, Cofee machines ...",
        Administration:"Administration",
        des5:"Instant current month upgrades",
    },
]

export default Flexiblepricedata;