const Flexiblepricedata=[
    // {
    //     images:"images/flaxible-price-image1.png",
    //     price:"$20",
    //     title:"Daily Pass",
    //     des:"Our Best Plan for Individuals",
    //     WorkingHours:"Working Hours",
    //     des2:"One Time 24 hours access",
    //     MeetingRoom:"Meeting Room",
    //     des3:"Additional charge $5/Per hour",
    //     Essentials:"Essentials",
    //     des4:"Internet, A/C, Cofee machines ...",
    //     Administration:"Administration",
    //     des5:"Instant current month upgrades",
    // },
    // {
    //     images:"images/flaxible-price-image2.png",
    //     price:"$20",
    //     title:"Daily Pass",
    //     des:"Our Best Plan for Individuals",
    //     WorkingHours:"Working Hours",
    //     des2:"One Time 24 hours access",
    //     MeetingRoom:"Meeting Room",
    //     des3:"Additional charge $5/Per hour",
    //     Essentials:"Essentials",
    //     des4:"Internet, A/C, Cofee machines ...",
    //     Administration:"Administration",
    //     des5:"Instant current month upgrades",
    // },
    // {
    //     images:"images/flaxible-price-image3.png",
    //     price:"$20",
    //     title:"Daily Pass",
    //     des:"Our Best Plan for Individuals",
    //     WorkingHours:"Working Hours",
    //     des2:"One Time 24 hours access",
    //     MeetingRoom:"Meeting Room",
    //     des3:"Additional charge $5/Per hour",
    //     Essentials:"Essentials",
    //     des4:"Internet, A/C, Cofee machines ...",
    //     Administration:"Administration",
    //     des5:"Instant current month upgrades",
    // },
    {
        whatweimage:"images/what-we-image1.jpeg",
        text:"DEDICATED",
        price:"₹6500",
        title:"Dedicated Desks",
        des:"Rs. 6500 per person per month",
        des2:"Fixed desk in open area",
        Choose_btn:"https://rzp.io/l/8osfC34",
    },
    {
        whatweimage:"images/what-we-image2.jpeg",
        text:"CABIN",   
        price:"₹11000",
        title:"Private Offices",
        des:"Rs. 11000 per person per month",
        des2:"Private cabin for you & your team",
        Choose_btn:"https://rzp.io/i/lwHtEvZHd",
    },
    {
        whatweimage:"images/what-we-image3.jpg",
        text:"DAY PASS",   
        price:"₹600",
        title:"DAY PASS",
        des:"Rs.600 per person per day",
        des2:"Your desk in the open area for 8 hours",
        Choose_btn:"https://rzp.io/l/UcSu1YD6oc",
        
    },
    {
        whatweimage:"images/what-we-image4.jpg",
        text:"VIRTUAL OFFICE",
        price:"₹9000",
        title:"Virtual Office",
        des:"Starting from Rs. 9000 per month",   
        des2:"Virtual office service",
        Choose_btn:"https://rzp.io/l/XY230CqICF",
    },
]

export default Flexiblepricedata;